version: '3.7'
services:
  mongodb:
    container_name: "mongodb"
    image: "mongo:6.0.6"
    restart: always
    command: --bind_ip_all --quiet
    ports:
      - 27017:27017
    networks:
      - b-network

  scanner:
    container_name: "scanner"
    build: .
    restart: always
    ports:
      - 6080:6080
    networks:
      - b-network

networks:
  b-network:
    driver: bridge