version: '3.7'
services:
  mongodb:
    container_name: "mongodb"
    image: "mongo:4.2.3"
    restart: always
    command: --bind_ip_all --quiet
    networks:
      - b-network

  scanner:
    container_name: "scanner"
    image: "scanner:latest"
    restart: always
    ports:
      - 6080:6080
    networks:
      - b-network

networks:
  b-network:
    driver: bridge