// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"
	queuejob "scanner/pkg/services/queueJob"

	mock "github.com/stretchr/testify/mock"
)

// QueueJob is an autogenerated mock type for the QueueJob type
type QueueJob struct {
	mock.Mock
}

// AddJob provides a mock function with given fields: ctx, j
func (_m *QueueJob) AddJob(ctx context.Context, j *queuejob.Job) error {
	ret := _m.Called(ctx, j)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *queuejob.Job) error); ok {
		r0 = rf(ctx, j)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Start provides a mock function with given fields:
func (_m *QueueJob) Start() {
	_m.Called()
}
