// Code generated by mockery v2.28.1. DO NOT EDIT.

package mocks

import (
	context "context"
	db "scanner/pkg/db"

	mock "github.com/stretchr/testify/mock"

	primitive "go.mongodb.org/mongo-driver/bson/primitive"
)

// ScanStore is an autogenerated mock type for the ScanStore type
type ScanStore struct {
	mock.Mock
}

// Add provides a mock function with given fields: ctx, v
func (_m *ScanStore) Add(ctx context.Context, v *db.Scan) (primitive.ObjectID, error) {
	ret := _m.Called(ctx, v)

	var r0 primitive.ObjectID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *db.Scan) (primitive.ObjectID, error)); ok {
		return rf(ctx, v)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *db.Scan) primitive.ObjectID); ok {
		r0 = rf(ctx, v)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(primitive.ObjectID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *db.Scan) error); ok {
		r1 = rf(ctx, v)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateCompleted provides a mock function with given fields: ctx, id
func (_m *ScanStore) UpdateCompleted(ctx context.Context, id primitive.ObjectID) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateError provides a mock function with given fields: ctx, id
func (_m *ScanStore) UpdateError(ctx context.Context, id primitive.ObjectID) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewScanStore interface {
	mock.TestingT
	Cleanup(func())
}

// NewScanStore creates a new instance of ScanStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewScanStore(t mockConstructorTestingTNewScanStore) *ScanStore {
	mock := &ScanStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
